import React from 'react';

// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css'
// own css files here
import "../styles/global.css"
// import components
import Layout from "../components/layout"
import Head from "next/head";
import NavbarBootstrap from '../components/navbar';

export default function App({Component, pageProps}) {
  return (
    <>
      <Head>
        <title>Be Well Health App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps}/>
      </Layout>
    </>

  );
}

